<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="5.3.2" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
    <PackageReference Include="System.Data.SQLite" Version="2.0.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="img\网格.png" />
    <Resource Include="img\全部.png" />
    <Resource Include="img\分类.png" />
    <Resource Include="img\动作游戏.png" />
    <Resource Include="img\角色扮演.png" />
    <Resource Include="img\策略游戏.png" />
    <Resource Include="img\射击游戏.png" />
    <Resource Include="img\未分类.png" />
    <Resource Include="img\档案.jpg" />
    <Resource Include="img\golden.png" />
    <Resource Include="img\silver.png" />
    <Resource Include="img\copper.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="temp_obj\**\*" />
    <EmbeddedResource Remove="temp_obj\**\*" />
    <None Remove="temp_obj\**\*" />
    <Page Remove="temp_obj\**\*" />
    <Resource Remove="temp_obj\**\*" />
    <ApplicationDefinition Remove="temp_obj\**\*" />
  </ItemGroup>

</Project>
